name: Run Postman Tests
on:
push:
branches: [ "dev" ]
pull_request:
branches: ["main]

jobs: 
test:
runs-on: ubuntu-latest

steps:
- name: Checkout repository
  uses: actions/checkout@v3
  
- name: Install Node.js
  uses: actions/setup-node@v3
  with:
    node-version: '18'

- name: Install Postman CLI
  run: npm install -g @postman/cli

- name: Run Postman Collection
  run: |
    postman collection run collections/Assurdly-Assurdly Reqres Tests.postman_collection.json
